name: terraform-pr

on:
  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  plan-dev:
    runs-on: ubuntu-latest

    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
      AWS_REGION: eu-central-1

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
          terraform_wrapper: false

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform fmt (check)
        working-directory: aws
        run: terraform fmt -check -diff -recursive

      - name: Init (dev)
        working-directory: aws/envs/dev
        run: terraform init -input=false -backend-config=backend.hcl

      - name: Validate (dev)
        working-directory: aws/envs/dev
        run: terraform validate -no-color

      - name: Plan (dev)
        working-directory: aws/envs/dev
        run: terraform plan -input=false -no-color -lock-timeout=5m